### ISSUE TITLE
SMS and iMessage

### ISSUE THREAD

**Issue by gforce4n6** [abrignoni/iLEAPP#177]
Hi! 

I had 23092 messages and it took 4 hours and 53 minutes to run iLEAPP with just the sms/iMessages options checked (everything. else unchecked). I was processing it locally in my computer. The image was a 55 GB full file system extraction from GrayKey. I am wondering if the bubble chat function (even though it is super gorgeous)  may be causing the slow down. If that is the case, I am wondering if there would be a way of having two options, the bubble chat (and that being deselected by default) and just displaying the sms/iMessages in a table and that way the user can select whatever they want depending on the time they have. 

thank you!

**Comment by ydkhatri** [comment]
If you can share the db, we could try to test this. You can share privately via email.

Also, last night I made most of iLEAPP python 3.9 compatible, which will be tremendously faster. Try it with the latest code with python 3.9 now and let me know. I am sure you will see a drastic reduction in processing time, as the SMS module uses the FileSeeker class quite a bit, and it can slow things down because of multiple repeated searches on the filesystem. For example, another rather SLOW module is the photosMetadata, which takes 21 min. on py 3.7 now only takes 2 min on 3.9.

**Comment by ydkhatri** [comment]
Actually no need to share the db, its going to be the attachments that slow it down (as noted above). Let me know how 3.9 goes.

**Comment by ydkhatri** [comment]
Closing this now, as I see your reply on twitter. 
18 min vs ~5 hrs is sweet!
