### ISSUE TITLE
Trace back error

### ISSUE THREAD

**Issue by Lou511** [abrignoni/iLEAPP#34]
Good morning Alexis.  While using the GUI, I noticed a trace back error.  The html report was created without an issues (I think).  The only thing I can think of is that an issue was encountered when creating the CSV report.  I don't see it anywhere in the directory containing the html report.  Here is the error:

```
C:\Tools\iLEAPP-master>python ileapp.py --gui
Traceback (most recent call last):
  File "ileapp.py", line 31, in <module>
    gui_event_loop(window)
  File "C:\Tools\iLEAPP-master\ileappGUI.py", line 89, in gui_event_loop
    html2csv(report_folder_base)
  File "C:\Tools\iLEAPP-master\ilapfuncs.py", line 5197, in html2csv
    soup = BeautifulSoup(data, "html.parser")
  File "C:\Program Files\Python37\lib\site-packages\bs4\__init__.py", line 286, in __init__
    markup = markup.read()
  File "C:\Program Files\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x94 in position 1403: invalid start byte
```

**Comment by agamdua** [comment]
Hey @Lou511! Thanks for reporting this issue.

Your assessment is absolutely correct, the report would have been generated absolutely correctly and failed only at the CSV generation step.

This seems like an encoding difference. Unfortunately encodings are quite tricky, since it is very specific to the file being used _and_ the OS it is being run on, so I am not able to reproduce it with my test data.

Based on some analysis, this seems like an issue where a specific Windows encoding (`Windows-1252`) is being used when the data is being read. I will see if I can make a pull request to gracefully handle this later this week, or at least fail better.

Would you be able to share what version of Windows you are using?

Ideally, if you could share data so we could reproduce it that would be amazing, but I understand you may not be able to.

**Comment by abrignoni** [comment]
The CSV option takes the html generated reports and converts them. I'm
pretty sure the issue has to do with the move from html to CSV. I thought
of the CSV option as a stopgap measure till a module could handle it at
artifact parsing time.

**Comment by agamdua** [comment]
@abrignoni 
> I'm pretty sure the issue has to do with the move from html to CSV.
yeah that is clear.

> I thought of the CSV option as a stopgap measure till a module could handle it at artifact parsing time.
ok - do you want to talk about a refactor for that in a separate issue, or is there an implication I am missing?

**Comment by abrignoni** [comment]
You are totally on it. There surely is a better way than converting the
html. Would love your thoughts on that as usual.

**Comment by agamdua** [comment]
Ok, going to open a separate issue later today with some thoughts about this. Have some ideas.
