### ISSUE TITLE
Integrating with Autopsy

### ISSUE THREAD

**Issue by WriteCodeEveryday** [abrignoni/iLEAPP#45]
Would it be possible to turn this into a module for Autopsy?

The standard Android Analyzer module is decent, but they don't have a dedicated iOS Analyzer.

**Comment by ydkhatri** [comment]
Possible with limited features, but unlikely due to the reasons stated on Autopsy's website:
https://www.sleuthkit.org/autopsy/docs/api-docs/4.15.0/mod_dev_py_page.html

Autopsy uses Jython, which severely restricts what you can do. Main limitations are:

+ Limited to Python 2.7 (as of Autopsy 3.1.3)
+ Can't use Python libraries that have native code

**Comment by bcarrier** [comment]
FWIW: Some Autopsy modules simply run command line tools, parse their output, and make Autopsy artifacts.  Even though Autopsy is limited to Jython, I'd imagine that iLEAPP could be run as a command line tool on a data source and its output turned into Autopsy artifacts. 

Or, if some of the underlying scripts in iLEAPP operate on specific files, an Autopsy module could query for those files, save them to a temp folder, run the script on it, and bring the results back into the Autopsy UI.
