### ISSUE TITLE
python-magic-bin not available for ARM Mac

### ISSUE THREAD

**Issue by h4x0r** [abrignoni/iLEAPP#567]
pip installing requirements stopped with:

ERROR: Could not find a version that satisfies the requirement python-magic-bin==0.4.14 (from versions: none)
ERROR: No matching distribution found for python-magic-bin==0.4.14

I see that the spec does cater to ARM Mac:
python-magic==0.4.24; platform_system == "Linux"
python-magic-bin==0.4.14; platform_system == "Windows"
python-magic-bin==0.4.14; platform_system == "Darwin"
python-magic; platform_system == "Darwin" and platform_machine == "arm64"

So I've no idea why it still stopped with an error. Any idea please? Right now I just comment out the lines with python-magic-bin and it seems to work.

**Comment by JamesHabben** [comment]
pull request in R to address this it seems.

https://github.com/abrignoni/RLEAPP/pull/171

**Comment by abrignoni** [comment]
Getting this error on a brand new ARM mac:
ImportError('failed to find libmagic.  Check your installation')

Any thoughts?

**Comment by abrignoni** [comment]
Ended up adding libmagic via MacPorts. Worked.

**Comment by Johann-PLW** [comment]
Also works with brew. 
Have a look to Discussion #622

**Comment by JamesHabben** [comment]
I think I have seen this on a windows also. May need an adjustment to the requirements text file

**Comment by Johann-PLW** [comment]
As mentioned on the PyPI for python-magic web page, this module is a simple wrapper around the libmagic C library, which must also be installed.
More than just adjusting the requirements.txt file, I think we should consider an alternative solution, as it may become a little more complicated for the user to have to install brew or macports on Mac or DLLs on Windows in order to use iLEAPP.
As the magic module is not widely used in iLEAPP, we could stop using it and use instead an alternative one which appears to offer identical functionality for retrieving the extension and mime type of a file.
This is the filetype module, which is simply installed with `pip install filetype` and requires no special dependencies. This wouldn't require too many changes to the current code.

With python-magic module:
`mimetype = magic.from_file(filepath, mime=True)`
Output examples: image/jpeg, image/png, audio/amr, audio/x-wav, video/mp4

With the new filetype module:
`mimetype = filetype.guess(filepath).mime`
Output examples: image/jpeg, image/png, audio/amr, audio/x-wav, video/mp4

 New signatures can easily be added as required.

@abrignoni If you think this is a possible alternative, I'm willing to create a branch in my own repository for testing purposes.

**Comment by abrignoni** [comment]
I agree. If we can confirm there are no scripts that need any special
functionality that filetype couldn't give then we should change it.

**Comment by Johann-PLW** [comment]
python-magic is only used in 
- ilapfuncs.py for the media_to_html function
- fsCachedData.py to indicate the filetype in a column of the HTML report
- protonMail.py (this part of the code could use the media_to_html)

**Comment by Johann-PLW** [comment]
@abrignoni @JamesHabben @stark4n6 
If you want, you can test this fork of iLEAPP (https://github.com/Johann-PLW/iLEAPP/tree/filetype) where python-magic module was replaced with filetype module.
I have not observed any major differences, except with the fsCachedData parser. The Mime Type column is empty when filetype module does not recognise the file header. But this is something we could fix by adding the missing signatures.

- With python-magic module:
<img width="1359" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/471b4439-2611-42d4-bff7-1c099b0cc255">


- With filetype module:
<img width="1359" alt="image" src="https://github.com/abrignoni/iLEAPP/assets/27498476/16d4eed3-cd30-4dd6-89c4-c00aa1f0aa92">

**Comment by abrignoni** [comment]
Lets change it. No need to have a dependency that causes issues for no benefit.
This helps a lot.
