### ISSUE TITLE
v1.19.4 GUI version not working

### ISSUE THREAD

**Issue by Rihe-hub** [abrignoni/iLEAPP#789]
Hello,

There is an issue with the GUI Windows version when parsing an extraction, screen remains empty.
<img width="669" alt="ileapp_1 19 4" src="https://github.com/user-attachments/assets/d9ad471a-c967-48f8-b1bf-ff740f87e8fd">

No problem with the Windows GUI version when building manually the GUI version from source code.

Thanks

**Comment by Rihe-hub** [comment]
I was able to reproduce the "empty screen" issue by modifying "console=True" to "console=False" in ileappGUI.spec file

When building GUI Windows version with "console=True", it's working fine (or at least log console is working)

**Comment by Johann-PLW** [comment]
Hi @Rihe-hub,

Thank you very much for reporting this issue.
You're right. I assumed that the problem came from xleappGUI.spec file.
I changed the 'console' parameter with the latest release as the hide-early parameter does not work anymore.
I will rebuild new binaries as soon as I will have access to a Windows Computer.

**Comment by Johann-PLW** [comment]
This was fixed and an updated file has just been uploaded.
Thank you very much.
